apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.name }}-service
spec:
  selector:
    app: {{ .Values.global.name }}
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 3000
